// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsWRh23hpzUfo5w_LevsrIa_IOlvPaYfg',
    appId: '1:726009987795:web:dae2624ec0c6031fe10a26',
    messagingSenderId: '726009987795',
    projectId: 'mynotes-flufire',
    authDomain: 'mynotes-flufire.firebaseapp.com',
    storageBucket: 'mynotes-flufire.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc8TIC-KL5b8pwpo_jXqmUGDJFUkSeG-k',
    appId: '1:726009987795:android:2ba989bbad037e38e10a26',
    messagingSenderId: '726009987795',
    projectId: 'mynotes-flufire',
    storageBucket: 'mynotes-flufire.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCJHAQEsncVcVsPChzpAFYTX5-Iotaxo4',
    appId: '1:726009987795:ios:d57c5bc679536fc6e10a26',
    messagingSenderId: '726009987795',
    projectId: 'mynotes-flufire',
    storageBucket: 'mynotes-flufire.appspot.com',
    iosClientId: '726009987795-tsmk6o6vqthqh066eanuopa7vvc3e60m.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCJHAQEsncVcVsPChzpAFYTX5-Iotaxo4',
    appId: '1:726009987795:ios:d57c5bc679536fc6e10a26',
    messagingSenderId: '726009987795',
    projectId: 'mynotes-flufire',
    storageBucket: 'mynotes-flufire.appspot.com',
    iosClientId: '726009987795-tsmk6o6vqthqh066eanuopa7vvc3e60m.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
